name: cerita_rakyat
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.11.0

flutter:
  uses-material-design: true

  assets:
  - assets/images/comedy.png
  - assets/images/flower.png
  - assets/images/sword.png
  - assets/images/book.png
  - assets/images/ghost.png
  - assets/images/admin.png
  - assets/images/revan.jpg
  - assets/images/book_2.png
  

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/book.png"


  
